[package]
name = "rml_rtmp"
description = "Rust library for handling aspects of the RTMP protocol."
version = "0.1.0"
authors = ["Matthew Shapiro <me@mshapiro.net>"]
repository = "https://github.com/KallDrexx/rust-media-libs"
license = "MIT"

[dependencies]
byteorder = "1.2.1"
rand = "0.3"
failure = "0.1.1"
ring = "0.12.1"